# Generated by Django 4.2.5 on 2023-09-22 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_iteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='summary_message',
        ),
        migrations.RemoveField(
            model_name='user',
            name='system_message',
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_message', models.TextField(blank=True, null=True)),
                ('summary_message', models.TextField(blank=True, null=True)),
                ('iteration', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='chatcmpl',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adventure'),
        ),
        migrations.AlterField(
            model_name='message',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adventure'),
        ),
    ]
