# Generated by Django 4.2.5 on 2023-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_iteration_remove_user_summary_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='adventure',
            name='start_message',
            field=models.TextField(default='Please start.'),
        ),
        migrations.AddField(
            model_name='chatcmpl',
            name='messages',
            field=models.ManyToManyField(to='core.message'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='system_message',
            field=models.TextField(default='You are an assistant.'),
        ),
    ]
