# Generated by Django 4.2.5 on 2023-09-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_text_message_content_adventure_start_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcmpl',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='chatcmpl',
            new_name='chatcmpls',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='adventure',
            name='start_message',
            field=models.TextField(default='You may start the story however you like.'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='system_message',
            field=models.TextField(default="You are a DnD Dungeon Master. You are creating a new adventure for your user. You either respond to the user's action or create a new event or action for user if the user is not sure what to do next.  Give only 2 to 3 sentences, do not list actions for user to choose from."),
        ),
    ]
