# Generated by Django 4.2.5 on 2023-09-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_users_chatcmpl_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcmpl',
            name='kind',
            field=models.CharField(choices=[('M', 'Message'), ('S', 'Summary')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('A', 'Assistant'), ('U', 'User'), ('S', 'System'), ('F', 'Function')], max_length=1),
        ),
    ]
