# Generated by Django 4.2.5 on 2023-09-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatcmpl_kind_alter_message_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcmpl',
            old_name='user',
            new_name='adventure',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='adventure',
        ),
    ]
