# Generated by Django 4.2.5 on 2023-09-23 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_chatcmpl_adventure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='summary_message',
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('chatcmpl_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_responded', to='core.chatcmpl')),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='summary_taken',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_supplied', to='core.summary'),
        ),
        migrations.AddField(
            model_name='chatcmpl',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.summary'),
        ),
    ]
