# Generated by Django 4.2.5 on 2023-09-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_adventure_summary_message_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='chatcmpl_from',
            new_name='chatcmpl_responded',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='summary_taken',
        ),
        migrations.RemoveField(
            model_name='chatcmpl',
            name='summary',
        ),
        migrations.AddField(
            model_name='adventure',
            name='summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.summary'),
        ),
        migrations.AddField(
            model_name='chatcmpl',
            name='summary_supplied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatcmpl_supplied', to='core.summary'),
        ),
    ]
