# Generated by Django 4.2.5 on 2023-09-24 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_choice_completion_tokens_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chatcmpls',
            new_name='chatcmpl',
        ),
        migrations.RemoveField(
            model_name='chatcmpl',
            name='summary_supplied',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='chatcmpl_responded',
        ),
        migrations.AddField(
            model_name='adventure',
            name='latest_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_adventure', to='core.message'),
        ),
        migrations.AddField(
            model_name='chatcmpl',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.summary'),
        ),
        migrations.AddField(
            model_name='choice',
            name='summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.summary'),
        ),
        migrations.AddField(
            model_name='message',
            name='prev',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='core.message'),
        ),
    ]
