# Generated by Django 4.2.5 on 2023-09-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_chatcmpls_choice_chatcmpl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='iteration',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='start_message',
            field=models.TextField(blank=True, default='You may start the story however you like.'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='system_message',
            field=models.TextField(blank=True, default="You are a DnD Dungeon Master. You are creating a new adventure for your user. You either respond to the user's action or create a new event or action for user if the user is not sure what to do next.  Give only 2 to 3 sentences, do not list actions for user to choose from."),
        ),
    ]
