# Generated by Django 4.2.5 on 2023-10-06 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_adventure_iteration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('knowledge', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('system_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SceneNpc',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('character', models.TextField()),
                ('knowledges', models.ManyToManyField(to='core.knowledge')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scene')),
            ],
        ),
        migrations.CreateModel(
            name='SceneRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npcs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.scene')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SceneNpcAdventurePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adventure')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scenenpc')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scenerunner')),
            ],
        ),
    ]
