# Generated by Django 4.2.5 on 2023-10-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_scenenpc_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenenpcadventurepair',
            name='knowledge_selection_token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scenenpc',
            name='index',
            field=models.PositiveIntegerField(),
        ),
    ]
