# Generated by Django 4.2.5 on 2023-10-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_scenenpcadventurepair_knowledge_selection_token_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenenpc',
            name='knowledges',
            field=models.ManyToManyField(related_name='npcs', to='core.knowledge'),
        ),
        migrations.AlterField(
            model_name='scenenpc',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='core.scene'),
        ),
    ]
