# Generated by Django 4.2.5 on 2023-10-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_scenenpc_knowledges_alter_scenenpc_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenenpcadventurepair',
            name='adventure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.adventure'),
        ),
        migrations.AlterField(
            model_name='scenerunner',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scene'),
        ),
    ]
